# Site settings
# These are used to personalize your new site.
title: Matthew Yanzer # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2021)
  <br /><br />
  [View my Resume](Updated Resume.docx)
  <br /><br />
repository: "MattYanzer/csci-portfolio"
github_username:  MattYanzer # update with your username

# Build setting
theme: jekyll-theme-minimal

